use std::{
    env,
    fs,
    path::{Path, PathBuf},
};

use robius_share::{Result, ShareSheet};

fn main() -> Result<()> {
    let mut args = env::args().skip(1);
    let Some(case) = args.next() else {
        print_usage();
        return Ok(());
    };

    match case.as_str() {
        "text" => {
            ShareSheet::new()
                .set_title("Robius share example")
                .set_subject("Text payload")
                .add_text("Robius share example text")
                .share()
        }
        "url" => {
            ShareSheet::new()
                .set_title("Robius share example")
                .set_subject("URL payload")
                .add_url("https://robius.rs/")
                .share()
        }
        "file" => {
            let path = args.next().map(PathBuf::from).unwrap_or_else(example_file_path);
            ensure_example_file(&path)?;
            ShareSheet::new()
                .set_title("Robius share example")
                .set_subject("File payload")
                .add_file_with_mime_type(path, "text/plain")
                .share()
        }
        "mixed" => {
            let path = args.next().map(PathBuf::from).unwrap_or_else(example_file_path);
            ensure_example_file(&path)?;
            ShareSheet::new()
                .set_title("Robius share example")
                .set_subject("Mixed payload")
                .add_text("Robius share example mixed payload")
                .add_url("https://robius.rs/")
                .add_file_with_mime_type(path, "text/plain")
                .share()
        }
        _ => {
            print_usage();
            Ok(())
        }
    }
}

fn print_usage() {
    eprintln!("usage: cargo run -p robius-share --example share_example -- <text|url|file|mixed> [file_path]");
}

fn example_file_path() -> PathBuf {
    env::temp_dir().join("robius-share-example.txt")
}

fn ensure_example_file(path: &Path) -> Result<()> {
    if path.exists() {
        return Ok(());
    }

    fs::write(
        path,
        "This file was generated by the robius-share CLI example.\n",
    )?;
    Ok(())
}
