/* This file is compiled by build.rs. */

/* This was initially generated by Codex GPT 5.5 and Claude Code Opus 4.7
 * but with heavy edits and review from Kevin.
 */

package robius.file_picker;

import android.Manifest;
import android.app.Activity;
import android.app.Fragment;
import android.app.FragmentTransaction;
import android.content.ActivityNotFoundException;
import android.content.ContentResolver;
import android.content.ContentValues;
import android.content.Intent;
import android.content.pm.PackageManager;
import android.database.Cursor;
import android.media.MediaScannerConnection;
import android.net.Uri;
import android.os.Build;
import android.os.Looper;
import android.provider.DocumentsContract;
import android.provider.OpenableColumns;
import android.os.Environment;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.io.IOException;
import java.io.OutputStream;
import java.util.List;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.atomic.AtomicBoolean;

public class FilePickerFragment extends Fragment {
    private static final int REQUEST_CODE = 0x526f;
    private static final int RESULT_ERROR = -2;
    private static final int MEDIA_KIND_NONE = 0;
    private static final int MEDIA_KIND_PHOTO = 1;
    private static final int MEDIA_KIND_VIDEO = 2;
    private static final int MEDIA_KIND_PHOTO_OR_VIDEO = 3;
    private static final int API_Q = 29;
    private static final String FRAGMENT_TAG = "robius.file_picker.FilePickerFragment";
    private static final String ACTION_PICK_IMAGES = "android.provider.action.PICK_IMAGES";
    private static final String COLUMN_DISPLAY_NAME = "_display_name";
    private static final String COLUMN_MIME_TYPE = "mime_type";
    private static final String COLUMN_RELATIVE_PATH = "relative_path";
    private static final String COLUMN_IS_PENDING = "is_pending";

    private static final String EXTERNAL_STORAGE_AUTHORITY = "com.android.externalstorage.documents";

    private long callbackPtr;
    private boolean save;
    private String title;
    private String fileName;
    private String sourcePath;
    private byte[] sourceData;
    private String mimeType;
    private String[] mimeTypes;
    private String initialLocationDir;
    private int mediaKind;
    private boolean launched;

    /*
     * The name and signature of this function must be kept in sync with `RUST_CALLBACK_NAME`,
     * and `RUST_CALLBACK_SIGNATURE` respectively.
     */
    private static native void rustCallback(
        long callbackPtr,
        int resultCode,
        String uri,
        String displayName,
        String mimeType,
        long size);

    public FilePickerFragment() {
        this.callbackPtr = 0;
    }

    public FilePickerFragment(
            long callbackPtr,
            boolean save,
            String title,
            String fileName,
            String sourcePath,
            byte[] sourceData,
            String mimeType,
            String[] mimeTypes,
            String initialLocationDir,
            int mediaKind) {
        this.callbackPtr = callbackPtr;
        this.save = save;
        this.title = title;
        this.fileName = fileName;
        this.sourcePath = sourcePath;
        this.sourceData = sourceData;
        this.mimeType = mimeType;
        this.mimeTypes = mimeTypes;
        this.initialLocationDir = initialLocationDir;
        this.mediaKind = mediaKind;
        this.launched = false;
    }

    public static boolean show(
            Activity activity,
            long callbackPtr,
            boolean save,
            String title,
            String fileName,
            String sourcePath,
            String mimeType,
            String[] mimeTypes,
            String initialLocationDir) {
        FilePickerFragment fragment = new FilePickerFragment(
                callbackPtr,
                save,
                title,
                fileName,
                sourcePath,
                null,
                mimeType,
                mimeTypes,
                initialLocationDir,
                MEDIA_KIND_NONE);

        return showFragment(activity, fragment);
    }

    public static boolean saveData(
            Activity activity,
            long callbackPtr,
            String fileName,
            String mimeType,
            String[] mimeTypes,
            String title,
            String initialLocationDir,
            byte[] sourceData) {
        FilePickerFragment fragment = new FilePickerFragment(
                callbackPtr,
                true,
                title,
                fileName,
                null,
                sourceData,
                mimeType,
                mimeTypes,
                initialLocationDir,
                MEDIA_KIND_NONE);

        return showFragment(activity, fragment);
    }

    public static boolean pickMedia(
            Activity activity,
            long callbackPtr,
            int mediaKind,
            String title) {
        FilePickerFragment fragment = new FilePickerFragment(
                callbackPtr,
                false,
                title,
                null,
                null,
                null,
                null,
                null,
                null,
                mediaKind);

        return showFragment(activity, fragment);
    }

    public static boolean saveToDownloads(
            Activity activity,
            long callbackPtr,
            String fileName,
            String mimeType,
            String sourcePath) {
        if (!canWriteDownloadsDirectly(activity)) {
            return show(activity, callbackPtr, true, null, fileName, sourcePath, mimeType, null, null);
        }

        new Thread(() -> {
            int resultCode = Activity.RESULT_OK;
            String uri = null;

            try {
                uri = saveToDownloadsInner(activity, fileName, mimeType, sourcePath);
                if (uri == null) {
                    resultCode = RESULT_ERROR;
                }
            } catch (Throwable e) {
                resultCode = RESULT_ERROR;
            }

            rustCallback(callbackPtr, resultCode, uri, null, null, -1);
        }, "robius-file-picker-save-to-downloads").start();
        return true;
    }

    private static boolean showFragment(Activity activity, FilePickerFragment fragment) {
        if (Looper.myLooper() == Looper.getMainLooper()) {
            return showFragmentOnUiThread(activity, fragment);
        }

        AtomicBoolean result = new AtomicBoolean(false);
        CountDownLatch uiThreadFinished = new CountDownLatch(1);
        activity.runOnUiThread(() -> {
            try {
                result.set(showFragmentOnUiThread(activity, fragment));
            } finally {
                uiThreadFinished.countDown();
            }
        });

        boolean interrupted = false;
        while (true) {
            try {
                uiThreadFinished.await();
                break;
            } catch (InterruptedException e) {
                interrupted = true;
            }
        }
        if (interrupted) {
            Thread.currentThread().interrupt();
        }
        return result.get();
    }

    private static boolean showFragmentOnUiThread(Activity activity, FilePickerFragment fragment) {
        if (activity.isFinishing() || activity.isDestroyed()) {
            return false;
        }

        FragmentTransaction transaction = null;
        List<Fragment> fragments = activity.getFragmentManager().getFragments();
        if (fragments != null) {
            for (Fragment existing : fragments) {
                if (!(existing instanceof FilePickerFragment)) {
                    continue;
                }

                FilePickerFragment picker = (FilePickerFragment) existing;
                if (picker.hasCallback()) {
                    return false;
                }

                if (transaction == null) {
                    transaction = activity.getFragmentManager().beginTransaction();
                }
                transaction.remove(picker);
            }
        }

        if (transaction == null) {
            transaction = activity.getFragmentManager().beginTransaction();
        }
        transaction
                .add(fragment, FRAGMENT_TAG)
                .commitNowAllowingStateLoss();
        return true;
    }

    @Override
    public void onResume() {
        super.onResume();

        if (!launched && callbackPtr != 0) {
            launched = true;
            launchPicker();
        }
    }

    @Override
    public void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);

        if (requestCode != REQUEST_CODE) {
            return;
        }

        // If the activity was destroyed while the picker was visible,
        // we must still deliver a result to prevent hangs/leaks in the JNI callback.
        Activity activity = getActivity();
        if (activity == null) {
            finish(RESULT_ERROR, null);
            return;
        }
        if (resultCode != Activity.RESULT_OK || data == null) {
            finish(resultCode, null);
            return;
        }
        final Uri dataUri = data.getData();
        if (dataUri == null) {
            finish(resultCode, null);
            return;
        }

        // Capture the resolver here on the UI thread; the background save thread
        // must not call `getActivity()`, as it may have become null by then.
        final ContentResolver resolver = activity.getContentResolver();

        int flags = data.getFlags()
                & (Intent.FLAG_GRANT_READ_URI_PERMISSION
                | Intent.FLAG_GRANT_WRITE_URI_PERMISSION);
        if (flags != 0) {
            try {
                resolver.takePersistableUriPermission(dataUri, flags);
            } catch (SecurityException ignored) {}
        }

        final int okCode = resultCode;
        final String uriString = dataUri.toString();

        if (save) {
            // The user has chosen a destination, so the save operation now owns
            // the callback. Destroying this fragment while copying should not
            // report cancellation.
            final long callback = claimCallback();
            if (callback == 0) {
                removeSelf();
                return;
            }

            // Writing the file might be slow, so don't do it on the main UI thread.
            final Activity callbackActivity = activity;
            new Thread(
                () -> {
                    boolean ok = copySourceToUri(resolver, dataUri);
                    rustCallback(
                            callback,
                            ok ? okCode : RESULT_ERROR,
                            ok ? uriString : null,
                            null,
                            null,
                            -1);
                    callbackActivity.runOnUiThread(this::removeSelf);
                },
                "robius-file-picker-save"
            ).start();
        } else {
            // For a picked file, report the provider's display name, MIME type,
            // and size so the caller doesn't have to guess.
            String displayName = queryDisplayName(resolver, dataUri);
            String mimeType = resolver.getType(dataUri);
            long size = querySize(resolver, dataUri);
            finish(okCode, uriString, displayName, mimeType, size);
        }
    }

    private void launchPicker() {
        if (mediaKind != MEDIA_KIND_NONE) {
            launchMediaPicker();
            return;
        }

        Intent intent = new Intent(
                save ? Intent.ACTION_CREATE_DOCUMENT : Intent.ACTION_OPEN_DOCUMENT);
        intent.addCategory(Intent.CATEGORY_OPENABLE);
        intent.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION
                | Intent.FLAG_GRANT_WRITE_URI_PERMISSION
                | Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION);
        intent.setType(mimeType != null && !mimeType.isEmpty() ? mimeType : "*/*");

        if (mimeTypes != null && mimeTypes.length > 0) {
            intent.putExtra(Intent.EXTRA_MIME_TYPES, mimeTypes);
        }

        if (save && fileName != null && !fileName.isEmpty()) {
            intent.putExtra(Intent.EXTRA_TITLE, fileName);
        }

        // Hint the initial folder (e.g. Downloads). EXTRA_INITIAL_URI is honored
        // from API 26+; older systems and some providers simply ignore it.
        if (initialLocationDir != null && !initialLocationDir.isEmpty()) {
            Uri initialUri = DocumentsContract.buildDocumentUri(
                    EXTERNAL_STORAGE_AUTHORITY, "primary:" + initialLocationDir);
            intent.putExtra(DocumentsContract.EXTRA_INITIAL_URI, initialUri);
        }

        if (title != null && !title.isEmpty()) {
            intent = Intent.createChooser(intent, title);
        }

        try {
            startActivityForResult(intent, REQUEST_CODE);
        } catch (ActivityNotFoundException e) {
            finish(RESULT_ERROR, null);
        }
    }

    private void launchMediaPicker() {
        // Prefer the modern Photo Picker when available, based on SDK version
        // which is for some reason more reliable than querying it.
        if (photoPickerAvailable()) {
            Intent intent = new Intent(ACTION_PICK_IMAGES);
            String mediaMimeType = mediaMimeType(mediaKind);
            if (mediaMimeType != null) {
                // Restrict to photos or videos ( omitting the type shows both)
                intent.setType(mediaMimeType);
            }
            try {
                startActivityForResult(intent, REQUEST_CODE);
                return;
            } catch (ActivityNotFoundException e) {
                // Claimed available but couldn't launch; fall through to the
                // document-picker fallback below.
            }
        }

        launchMediaDocumentFallback();
    }

    private void launchMediaDocumentFallback() {
        Intent intent = new Intent(Intent.ACTION_OPEN_DOCUMENT);
        intent.addCategory(Intent.CATEGORY_OPENABLE);
        intent.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION
                | Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION);

        if (mediaKind == MEDIA_KIND_PHOTO_OR_VIDEO) {
            intent.setType("*/*");
            intent.putExtra(
                    Intent.EXTRA_MIME_TYPES,
                    new String[] { "image/*", "video/*" });
        } else {
            intent.setType(mediaMimeType(mediaKind));
        }

        if (title != null && !title.isEmpty()) {
            intent = Intent.createChooser(intent, title);
        }

        try {
            startActivityForResult(intent, REQUEST_CODE);
        } catch (ActivityNotFoundException e) {
            finish(RESULT_ERROR, null);
        }
    }

    /** Whether the system Photo Picker (`ACTION_PICK_IMAGES`) is available. */
    private static boolean photoPickerAvailable() {
        // Native on Android 13+ (API 33).
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
            return true;
        }
        // Backported to Android 11/12 (API 30-32) through a Google Play system
        // update, detected via the R SDK extension version.
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.R) {
            return photoPickerBackportAvailable();
        }
        return false;
    }

    // Isolated so the API-30 `SdkExtensions` symbol is never reached on older
    // devices (this method is only called when SDK_INT >= 30).
    private static boolean photoPickerBackportAvailable() {
        return android.os.ext.SdkExtensions.getExtensionVersion(Build.VERSION_CODES.R) >= 2;
    }

    private static String mediaMimeType(int mediaKind) {
        switch (mediaKind) {
            case MEDIA_KIND_PHOTO:
                return "image/*";
            case MEDIA_KIND_VIDEO:
                return "video/*";
            default:
                return null;
        }
    }

    @Override
    public void onDestroy() {
        super.onDestroy();
        // If the fragment is destroyed before a result was delivered,
        // deliver a cancellation result to the native callback, which ensures
        // that it always runs exactly once.
        long callback = claimCallback();
        if (callback != 0) {
            rustCallback(callback, Activity.RESULT_CANCELED, null, null, null, -1);
        }
    }

    private synchronized long claimCallback() {
        long callback = callbackPtr;
        callbackPtr = 0;
        return callback;
    }

    private synchronized boolean hasCallback() {
        return callbackPtr != 0;
    }

    private void finish(int resultCode, String uri) {
        finish(resultCode, uri, null, null, -1);
    }

    private void finish(int resultCode, String uri, String displayName, String mimeType, long size) {
        long callback = claimCallback();

        if (callback != 0) {
            rustCallback(callback, resultCode, uri, displayName, mimeType, size);
        }

        removeSelf();
    }

    private void removeSelf() {
        if (getFragmentManager() != null) {
            getFragmentManager()
                    .beginTransaction()
                    .remove(this)
                    .commitAllowingStateLoss();
        }
    }

    private static String queryDisplayName(ContentResolver resolver, Uri uri) {
        return queryString(resolver, uri, OpenableColumns.DISPLAY_NAME);
    }

    private static String queryString(ContentResolver resolver, Uri uri, String column) {
        String[] projection = { column };
        try (Cursor cursor = resolver.query(uri, projection, null, null, null)) {
            if (cursor != null && cursor.moveToFirst()) {
                int index = cursor.getColumnIndex(column);
                if (index >= 0 && !cursor.isNull(index)) {
                    return cursor.getString(index);
                }
            }
        } catch (Exception ignored) {}
        return null;
    }

    private static long querySize(ContentResolver resolver, Uri uri) {
        String[] projection = { OpenableColumns.SIZE };
        try (Cursor cursor = resolver.query(uri, projection, null, null, null)) {
            if (cursor != null && cursor.moveToFirst()) {
                int index = cursor.getColumnIndex(OpenableColumns.SIZE);
                if (index >= 0 && !cursor.isNull(index)) {
                    return cursor.getLong(index);
                }
            }
        } catch (Exception ignored) {}
        return -1;
    }

    /**
     * Writes a `content://` URI's contents directly to a local file
     * without buffering it in memory.
     */
    public static boolean copyUriToFile(Activity activity, String uriString, String destPath) {
        try {
            Uri uri = Uri.parse(uriString);
            try (InputStream input = activity.getContentResolver().openInputStream(uri);
                 OutputStream output = new FileOutputStream(destPath)) {
                if (input == null) {
                    return false;
                }
                copy(input, output);
                return true;
            }
        } catch (Exception e) {
            return false;
        }
    }

    private boolean copySourceToUri(ContentResolver resolver, Uri uri) {
        if (sourceData != null) {
            try {
                writeDataToUri(resolver, sourceData, uri);
                return true;
            } catch (Exception e) {
                return false;
            }
        }

        if (sourcePath == null || sourcePath.isEmpty()) {
            return false;
        }

        try {
            copyFileToUri(resolver, sourcePath, uri);
            return true;
        } catch (Exception e) {
            return false;
        }
    }

    private static void writeDataToUri(
            ContentResolver resolver,
            byte[] data,
            Uri uri) throws IOException {
        try (OutputStream output = resolver.openOutputStream(uri, "w")) {
            if (output == null) {
                throw new IOException("could not open destination URI");
            }
            output.write(data);
        }
    }

    /**
     * Reads the full contents of a `content://` URI into memory.
     */
    public static byte[] readUriBytes(Activity activity, String uriString) {
        try {
            Uri uri = Uri.parse(uriString);
            try (InputStream input = activity.getContentResolver().openInputStream(uri);
                 java.io.ByteArrayOutputStream output = new java.io.ByteArrayOutputStream()) {
                if (input == null) {
                    return null;
                }
                copy(input, output);
                return output.toByteArray();
            }
        } catch (Exception e) {
            return null;
        }
    }

    private static String saveToDownloadsInner(
            Activity activity,
            String fileName,
            String mimeType,
            String sourcePath) throws IOException {
        if (Build.VERSION.SDK_INT >= API_Q) {
            return saveToDownloadsWithMediaStore(activity, fileName, mimeType, sourcePath);
        }

        return saveToDownloadsLegacy(activity, fileName, mimeType, sourcePath);
    }

    private static boolean canWriteDownloadsDirectly(Activity activity) {
        if (Build.VERSION.SDK_INT >= API_Q) {
            return true;
        }

        // API 26-28 still require the legacy write permission for saving a file
        // directly to the public Downloads directory. Otherwise, fallback to ACTION_CREATE_DOCUMENT.
        return activity.checkSelfPermission(Manifest.permission.WRITE_EXTERNAL_STORAGE)
                == PackageManager.PERMISSION_GRANTED;
    }

    private static String saveToDownloadsWithMediaStore(
            Activity activity,
            String fileName,
            String mimeType,
            String sourcePath) throws IOException {
        ContentResolver resolver = activity.getContentResolver();
        ContentValues values = new ContentValues();
        values.put(COLUMN_DISPLAY_NAME, fileName);
        values.put(COLUMN_MIME_TYPE, mimeType);
        values.put(COLUMN_RELATIVE_PATH, Environment.DIRECTORY_DOWNLOADS);
        values.put(COLUMN_IS_PENDING, 1);

        Uri uri = resolver.insert(downloadsExternalContentUri(), values);
        if (uri == null) {
            return null;
        }

        try {
            copyFileToUri(resolver, sourcePath, uri);
        } catch (IOException | RuntimeException e) {
            resolver.delete(uri, null, null);
            throw e;
        }

        ContentValues completedValues = new ContentValues();
        completedValues.put(COLUMN_IS_PENDING, 0);
        resolver.update(uri, completedValues, null, null);

        return uri.toString();
    }

    private static Uri downloadsExternalContentUri() throws IOException {
        try {
            // Keep API 29 symbols behind the SDK_INT guard so this class
            // can be legally loaded on any supported Android version (26+).
            return (Uri) Class.forName("android.provider.MediaStore$Downloads")
                    .getField("EXTERNAL_CONTENT_URI")
                    .get(null);
        } catch (ReflectiveOperationException | ClassCastException e) {
            throw new IOException("could not access MediaStore Downloads collection", e);
        }
    }

    private static String saveToDownloadsLegacy(
            Activity activity,
            String fileName,
            String mimeType,
            String sourcePath) throws IOException {
        File downloads = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS);
        if (!downloads.exists() && !downloads.mkdirs()) {
            throw new IOException("could not create Downloads directory");
        }

        File destination = uniqueFile(downloads, fileName);
        try (InputStream input = new FileInputStream(sourcePath);
             OutputStream output = new FileOutputStream(destination)) {
            copy(input, output);
        }

        MediaScannerConnection.scanFile(
                activity,
                new String[] { destination.getAbsolutePath() },
                new String[] { mimeType },
                null);

        return Uri.fromFile(destination).toString();
    }

    private static void copyFileToUri(
            ContentResolver resolver,
            String sourcePath,
            Uri uri) throws IOException {
        try (InputStream input = new FileInputStream(sourcePath);
             OutputStream output = resolver.openOutputStream(uri, "w")) {
            if (output == null) {
                throw new IOException("could not open destination URI");
            }
            copy(input, output);
        }
    }

    private static void copy(InputStream input, OutputStream output) throws IOException {
        byte[] buffer = new byte[64 * 1024];
        int len;
        while ((len = input.read(buffer)) != -1) {
            output.write(buffer, 0, len);
        }
    }

    private static File uniqueFile(File directory, String fileName) {
        File file = new File(directory, fileName);
        if (!file.exists()) {
            return file;
        }

        int dot = fileName.lastIndexOf('.');
        String stem = dot > 0 ? fileName.substring(0, dot) : fileName;
        String extension = dot > 0 ? fileName.substring(dot) : "";

        for (int index = 1; ; index++) {
            file = new File(directory, stem + " (" + index + ")" + extension);
            if (!file.exists()) {
                return file;
            }
        }
    }
}
